'use client';
import {useRef,useState} from 'react';
export default function Home(){
 const [mode,setMode]=useState('link'),[input,setInput]=useState(''),[status,setStatus]=useState(''),[title,setTitle]=useState(''),[text,setText]=useState(''),[busy,setBusy]=useState(false),[speed,setSpeed]=useState(1); const audio=useRef(null);
 async function go(){setBusy(true);setStatus('Henter og oversætter…');setText('');setTitle('');try{const r=await fetch('/api/process',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode,input})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Noget gik galt');setTitle(d.title||'Din tekst');setText(d.text);setStatus('Laver dansk oplæsning…');const a=await fetch('/api/speech',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:d.text})});if(!a.ok){const e=await a.json();throw new Error(e.error||'Kunne ikke lave lyd');}const blob=await a.blob();audio.current.src=URL.createObjectURL(blob);audio.current.playbackRate=speed;setStatus('Klar');await audio.current.play();}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 function seek(n){if(audio.current)audio.current.currentTime=Math.max(0,audio.current.currentTime+n)}
 function changeSpeed(v){setSpeed(v);if(audio.current)audio.current.playbackRate=v}
 return <main><header><div className="logo">◖</div><div><h1>Læs for mig</h1><p>Artikler og tekst. På dansk. I dine ører.</p></div></header><section className="card"><div className="tabs"><button className={mode==='link'?'active':''} onClick={()=>setMode('link')}>🔗 Link</button><button className={mode==='text'?'active':''} onClick={()=>setMode('text')}>Aa Tekst</button></div>{mode==='link'?<input value={input} onChange={e=>setInput(e.target.value)} placeholder="Indsæt link til en artikel…"/>:<textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Indsæt teksten her…" rows="9"/>}<button className="primary" disabled={busy||!input.trim()} onClick={go}>{busy?'Arbejder…':'▶  Læs op på dansk'}</button><div className="hint">Hele teksten oversættes – ikke et resumé.</div></section>{status&&<div className="status">{status}</div>}{text&&<section className="reader"><div className="eyebrow">NU LYTTER DU TIL</div><h2>{title}</h2><div className="controls"><button onClick={()=>seek(-15)}>↶<small>15</small></button><button className="play" onClick={()=>audio.current?.paused?audio.current.play():audio.current?.pause()}>▶</button><button onClick={()=>seek(15)}>↷<small>15</small></button><select value={speed} onChange={e=>changeSpeed(Number(e.target.value))}><option value="0.8">0,8×</option><option value="1">1×</option><option value="1.2">1,2×</option><option value="1.5">1,5×</option></select></div><audio ref={audio} controls/><details><summary>Vis dansk tekst</summary><p className="article">{text}</p></details></section>}<footer>Privat læseværktøj · AI-oversættelse kan indeholde fejl</footer></main>
}
